---

# THIS ASSUMES SPECIFIC AMI, SO IT DOES NOT DO THE FULL SETUP

- debug:
    msg: "-> consistency only"
  tags: [print_action]

#- debug:
#    msg: "{{ hostvars['localhost']['suite_hosts_lst'] }}"
#
#- debug:
#    msg: "{{ hostvars['localhost']['ec2_instance_info'] }}"
#
#- debug:
#    var: not exist

- name: Delete hosts file
  file:
    path: "{{ exp_consistency_hosts_file }}"
    state: absent

- name: Setup hosts file
  lineinfile:
    path: "{{ exp_consistency_hosts_file }}"  # Specify the path to your output file
    line: "{{ private_ip_lookup[item.private_dns_name] }}:8000"
    create: yes
  loop: "{{ hostvars['localhost']['suite_hosts_lst'] }}"
  vars:
    private_ip_lookup: "{{ hostvars['localhost']['ec2_instance_info'] | json_query('instances[*].{key: private_dns_name, value: private_ip_address}') | items2dict }}"

- name: remove existing rust version
  become: true
  apt:
    pkg:
      - rustc
    state: absent
    update_cache: yes

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
#  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
#  when: cargo_exists is failed
  shell: |
    source ~/.bashrc
    /tmp/sh.rustup.rs -y
  args:
    executable: /bin/bash
  tags:
    - rust

# TODO: enable parallel here
- name: Compile project
  ansible.builtin.shell: |
    source ~/.bashrc
    . "$HOME/.cargo/env"
    cargo build --release --features parallel
  args:
    chdir: "{{ exp_consistency_dir }}"
    executable: /bin/bash

# compile:
