---

audit_mnist:
  n_repetitions: 1
  host_types:
    compute:
      n: 4
      check_status: True
      init_roles:
        - setup-base
        - setup-mnist
      $CMD$:
        - main: bash {{ exp_code_dir }}/utils/experiment-runner.sh "{{ exp_code_dir }}" 0 2.0
        - main: bash {{ exp_code_dir }}/utils/experiment-runner.sh "{{ exp_code_dir }}" 1 2.0
        - main: bash {{ exp_code_dir }}/utils/experiment-runner.sh "{{ exp_code_dir }}" 2 2.0
        - main: bash {{ exp_code_dir }}/utils/experiment-runner.sh "{{ exp_code_dir }}" 3 2.0

  base_experiment:
    mpc:
      player_0_hostname: "[% exp_host_lst | json_query('[?host_type==`compute`].private_dns_name') | first %]"
      abs_path_to_code_dir: "{{ exp_code_dir }}"
      player_count: 4
      script_name: "audit_mnist"
      script_args:
        learning_rate: 0.0001
        n_num_threads: 16
        n_data_owners: 2
        sample_cutoff_size: -1
      protocol_setup: "rep4-ring-party"
      input_file_name: "{{ dataset_dir }}/mnist-small.zip"

$ETL$:
  extract_mpspdz:
    experiments: [first_exp]
    extractors:
      MpSpdzStderrExtractor:  {}
      MpSpdzResultExtractor: {}
      IgnoreExtractor: {}
    transformers: []
    loaders:
      CsvSummaryLoader:
        output_dir: etl_results