---
- ansible.builtin.debug:
    msg: "-> Setup for MP-SPDZ"
  tags: [print_action]

- name: "Delete MP-SPDZ subfolder from main code repo"
  ansible.builtin.file:
    state: absent
    path: "{{exp_code_dir}}/mp-spdz"
  
- name: "Create symbolic link to mp-spdz folder in AMI-defaults"
  ansible.builtin.file:
    state: link
    path: "{{exp_code_dir}}/mp-spdz"
    src: "{{mpspdz_precompile_home}}"

- name: make toy-example script executable
  ansible.builtin.file:
    path: "{{exp_code_dir}}/utils/toy-example.sh"
    mode: "777"
    state: file
