---

#instance_type: c5.9xlarge
instance_type: t2.xlarge
ec2_volume_size: 50

# AMI with Nikolay
#ec2_image_id: ami-0dc85e9d5743deec9	 # precompiled ami, #4
#ec2_volume_snapshot: snap-0c2123426c5ee42dd

ec2_image_id: ami-06dd92ecc74fdfb36
ec2_volume_snapshot: snap-0cdbc6abc38f4a630

instance_role: EC2WithS3Role

# does this override work?
#exp_code_dir: "{{ remote.dir }}/collaborative-zksnark/mpc-snarks"
#exp_hosts_file: "{{ exp_code_dir }}/data/vpc"

euler_job_minutes: 120 # individual job time
euler_cpu_cores: 4
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0
euler_gpu_min_mem_per_gpu_mb: 0
euler_gpu_model: ~ # if set to a specific GPU, then the euler_gpu_min_mem_per_gpu_mb is ignored
euler_env: gcc/8.2.0 python/3.9.9

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"
