---
- hosts: localhost
  name: "Create some EC2 instances and update hosts"
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:

    - name: Template inventory
      template:
        src: resources/inventory_aws_ec2.yml.j2
        dest: inventory/inventory_aws_ec2.yml
        mode: 0755
      vars:
        template_vars:
          instance_name: "{{test_host_name}}"
      

    - name: "Create instance"
      amazon.aws.ec2_instance:
        key_name: "{{aws_key_name}}"
        instance_type: "{{aws_instance_type}}"
        image_id: "ami-0d527b8c289b4af7f"
        wait: yes
        profile: "{{aws_target_profile}}"
        state: running
        name: "{{test_host_name}}"
        security_group: "{{aws_security_group}}"
        network:
          assign_public_ip: True
        volumes:
          - device_name: "/dev/sda1"
            ebs:
              volume_size: 30
              delete_on_termination: yes
    
    - name: Refresh inventory
      meta: refresh_inventory
  