


TIMER_LOAD_DATA = 99
TIMER_AUDIT = 100
TIMER_INFERENCE = 101
TIMER_TRAINING = 1102

TIMER_OUTPUT_COMMIT = 97
TIMER_INPUT_CONSISTENCY_CHECK = 98

TIMER_AUDIT_SHAP_BUILD_COALITIONS = 400
TIMER_AUDIT_SHAP_BUILD_Z_SAMPLES = 401
TIMER_AUDIT_SHAP_EVAL_SAMPLES = 402
TIMER_AUDIT_SHAP_MARGINAL_CONTRIBUTION = 403
TIMER_AUDIT_SHAP_LINREG = 404

TIMER_AUDIT_RS = 500