---
- ansible.builtin.debug:
    msg: "-> Setup for MP-SPDZ"
  tags: [print_action]


- name: "Delete MP-SPDZ subfolder from main code repo"
  ansible.builtin.file:
    state: absent
    path: "{{exp_code_dir}}/mp-spdz"

- name: "Create symbolic link to mp-spdz folder in AMI-defaults"
  ansible.builtin.file:
    state: link
    path: "{{exp_code_dir}}/mp-spdz"
    src: "{{mpspdz_precompile_home}}"

- ansible.builtin.debug:
    msg: "-> Setup for ML-example"
  tags: [print_action] 

- name: Setup awscli
  block:
    - name: Install packages
      become: yes
      apt:
        pkg:
          - zip
        update_cache: yes
    
    - name: Download awscli
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
    
    - name: Unpack awscli
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes
    
    - name: Install awscli via shell
      become: yes
      ansible.builtin.shell:
        chdir: /tmp
        cmd: ./aws/install
        creates: /usr/local/bin/aws

- name: Download Input for MNIST-Dataset
  block:
    - name: Setup Folder
      ansible.builtin.file:
        path: "{{exp_code_dir}}/custom-data"
        state: directory
    
    - name: Download Mnist dataset
      ansible.builtin.shell:
        cmd: "aws s3 sync s3://alexmandt-mpspdz-mlexample-input {{exp_code_dir}}/custom-data"

- name: Make ml-example script executable
  ansible.builtin.file:
    path: "{{exp_code_dir}}/utils/ml-stuff/ml-example.sh"
    mode: "777"
    state: file

- name: Make symbolic link from exp_code_dir/script_utils to Compiler folder of mp-spdz
  ansible.builtin.file:
    state: link
    path: "{{exp_code_dir}}/mp-spdz/Compiler/script_utils"
    src: "{{exp_code_dir}}/script_utils"
