---

instance_type: c5.9xlarge
#instance_type: t2.2xlarge
ec2_volume_size: 200

#ec2_image_id:  ami-0419cab1fa37ab915 # original ami
#ec2_volume_snapshot: snap-0b47b340fc299a25b

#ec2_image_id: ami-05401181765ee24c9	 # precompiled ami, #3
#ec2_volume_snapshot: snap-024cfffc9d4b0532d

#ec2_image_id: ami-0875ac3ffe3b458a3	 # precompiled ami, #4
#ec2_volume_snapshot: snap-0a2a18f55b6287597

ec2_image_id: ami-0a23d8c518e4a96ab	 # precompiled ami, #5
ec2_volume_snapshot: snap-0aa9ed955321b6330

instance_role: EC2WithS3Role

euler_job_minutes: 120 # individual job time
euler_cpu_cores: 4
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0
euler_gpu_min_mem_per_gpu_mb: 0
euler_gpu_model: ~ # if set to a specific GPU, then the euler_gpu_min_mem_per_gpu_mb is ignored
euler_env: gcc/8.2.0 python/3.9.9


euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"
