---
- name: Install MP-SPDZ
  hosts: all
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:
    - name: "Install prerequisites for MP-SPDZ"
      become: True
      ansible.builtin.apt:
        pkg:
          - automake
          - build-essential
          - git
          - libboost-dev
          - libboost-thread-dev
          - libntl-dev
          - libsodium-dev
          - libssl-dev
          - libtool
          - m4
          - python3
          - texinfo
          - yasm
        update_cache: yes
        state: present

    - name: "Check if MP-SPDZ is already cloned and compiled"
      ansible.builtin.stat:
        path: "{{git_repo_dest}}/mascot-party.x"
      register: mp_spdz_res

    - name: "Clone MP-SPDZ"
      ansible.builtin.git:
        repo: "{{target_repo}}"
        dest: "{{git_repo_dest}}"
        accept_hostkey: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      when: mp_spdz_res.stat.exists == False

    - name: "Skip \"Clone MP-SPDZ\""
      ansible.builtin.debug:
        msg: "MP-SPDZ already cloned, skipping"
      when: mp_spdz_res.stat.exists == True
    
    - name: "Check if MP-SPDZ libraries were compiled"
      ansible.builtin.stat:
        path: "{{git_repo_dest}}/semi2k-party.x"
      register: have_compiled_res

    - name: "Compile MP-SPDZ first mpir to get all libraries"
      community.general.make:
        chdir: "{{git_repo_dest}}"
        jobs: "{{make_job_nums}}"
        target: "tldr"
      when: have_compiled_res.stat.exists == False
      
    - name: "Compile MP-SPDZ fully"
      community.general.make:
        chdir: "{{git_repo_dest}}"
        jobs: "{{make_job_nums}}"
        target: "all"
      when: have_compiled_res.stat.exists == False
    

- name: "Create the AMI"
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:
    - name: "Create the AMI"
      amazon.aws.ec2_ami:
        profile: "{{aws_target_profile}}"
        wait: no
        instance_id: "{{hostvars['test-1']['my_host_instance_id']}}"
        name: "{{aws_ami_name}}"


          


  