---
- hosts: localhost
  name: "Create some EC2 instances and update hosts"
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:
    - name: "Create instance"
      amazon.aws.ec2_instance:
        key_name: "{{aws_key_name}}"
        instance_type: "{{aws_instance_type}}"
        image_id: "ami-0d527b8c289b4af7f"
        wait: yes
        profile: "{{aws_target_profile}}"
        state: running
        name: "{{test_host_name}}"
        security_group: "{{aws_security_group}}"
        network:
          assign_public_ip: True
      register: results
    
    - name: Create Inventory
      ansible.builtin.template:
        src: "{{playbook_dir}}/resources/my_hosts.template.j2"
        dest: "{{playbook_dir}}/inventory/my_hosts.yml"