---
- name: Install Prerequisites for mp-spdz
  hosts: all
  vars:
    mp_spdz_repo: git@github.com:data61/MP-SPDZ.git
    mp_spdz_home: "/home/{{ansible_user_id}}/mp-spdz"
  tasks:
    - name: Test
      ansible.builtin.debug:
        msg: "Hello World"
    - name: Install stuff for mp-spdz
      become: yes
      apt:
        pkg:
          - automake
          - build-essential
          - git
          - libboost-dev
          - libboost-thread-dev
          - libntl-dev
          - libsodium-dev
          - libssl-dev
          - libtool
          - m4 
          - python3 
          - texinfo
          - yasm
        update_cache: yes
    
    - name: Check if MP-SPDZ exists
      ansible.builtin.stat: 
        path: "{{mp_spdz_home}}/.it_exists"
      register: mp_spdz_existence_results


    - name: if MP-SPDZ already exists
      debug:
        msg: "MP-SPDZ already exists. Cloning will be skipped"
      when: mp_spdz_existence_results.stat.exists == True
    
    - name: Get MP-SPDZ
      ansible.builtin.git:
        repo: git@github.com:data61/MP-SPDZ.git
        dest: "{{mp_spdz_home}}"
        accept_hostkey: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      when: mp_spdz_existence_results.stat.exists == False
    
    - name: Create File to mark that MP-SPDZ already exists
      ansible.builtin.file:
        state: touch
        path: "{{mp_spdz_home}}/.it_exists"
      when: mp_spdz_existence_results.stat.exists == False

    

- name: Compile MP-SPDZ
  hosts: all
  vars:
    mp_spdz_repo: git@github.com:data61/MP-SPDZ.git
    mp_spdz_home: "/home/{{ansible_user_id}}/mp-spdz"
  tasks:
    - name: Compile mpir
      community.general.make:
        chdir: "{{mp_spdz_home}}"
        jobs: 8
        target: "mpir"
    
    - name: "Check if mascot-party.x exists"
      ansible.builtin.stat:
        path: "{{mp_spdz_home}}/mascot-party.x"
      register: st

    - name: "Compile mascot-x"
      community.general.make:
        chdir: "{{mp_spdz_home}}"
        jobs: 8
        target: "mascot-party.x"
      when: st.stat.exists == False

    - name: "Check if mama-party.x exists"
      ansible.builtin.stat:
        path: "{{mp_spdz_home}}/mama-party.x"
      register: st  

    - name: "Compile mama-party.x"
      community.general.make:
        chdir: "{{mp_spdz_home}}"
        jobs: 8
        target: "mama-party.x"
      when: st.stat.exists == False

    - name: "Compile spdz2k-party.x"
      community.general.make:
        chdir: "{{mp_spdz_home}}"
        jobs: 8
        target: "spdz2k-party.x"
    
    - name: "Compile semi-party.x"
      community.general.make:
        chdir: "{{ mp_spdz_home }}"
        jobs: 8
        target: "semi-party.x"
    
    - name: "Compile semi2k-party.x"
      community.general.make:
        chdir: "{{ mp_spdz_home }}"
        jobs: 8
        target: "semi2k-party.x"
