---
- hosts: localhost
  name: "Create some EC2 instances and update hosts"
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:
    - name: "Create instance"
      amazon.aws.ec2_instance:
        key_name: local-keys-2
        instance_type: t2.medium
        image_id: "ami-0d527b8c289b4af7f"
        wait: yes
        profile: "{{aws_target_profile}}"
        state: running
        name: "{{test_host_name}}"
        security_group: test-security-group
        network:
          assign_public_ip: True
      register: results
    
    - name: Create Inventory
      ansible.builtin.template:
        src: "{{playbook_dir}}/resources/my_hosts.template.j2"
        dest: "{{playbook_dir}}/inventory/my_hosts.yml"


- name: Rebuild inventory
  hosts: localhost
  gather_facts: False
  tasks:
    - ansible.builtin.meta: refresh_inventory


- name: "Execute test plays"
  ansible.builtin.import_playbook: "{{playbook_dir}}/size3.yml"


- name: "Destroy aws"
  hosts: localhost
  gather_facts: False
  vars_files:
    - "{{playbook_dir}}/site2_vars.yml"
  tasks:
    - name: "Terminate instance"
      amazon.aws.ec2_instance:
        state: absent
        profile: "{{aws_target_profile}}"
        name: "{{test_host_name}}"

    - name: "Delete generated inventory"
      ansible.builtin.file:
        state: absent
        path: "{{playbook_dir}}/inventory/my_hosts.yml"
