---

instance_type: c5.9xlarge
#instance_type: c5d.metal
#instance_type: t2.xlarge
ec2_volume_size: 300

#ec2_image_id: ami-0875ac3ffe3b458a3	 # precompiled ami, #4
#ec2_volume_snapshot: snap-0a2a18f55b6287597

#ec2_image_id: ami-05dc03650ed24f7b0	 # precompiled ami, #7
#ec2_volume_snapshot: snap-0a08a9c94b0f7d790

ec2_image_id: ami-0de4fd9c36db9b1a0
ec2_volume_snapshot: snap-0107bab5c3090dd87

# AMI from Nikolay
#ec2_image_id: ami-06dd92ecc74fdfb36
#ec2_volume_snapshot: snap-0cdbc6abc38f4a630

instance_role: EC2WithS3Role

# does this override work?
#exp_code_dir: "{{ remote.dir }}/mpc-consistency"
#exp_hosts_file: "{{ exp_code_dir }}/data/vpc"

#exp_spdz_dir: "{{ remote.dir }}/mpc-consistency"

euler_job_minutes: 120 # individual job time
euler_cpu_cores: 4
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0
euler_gpu_min_mem_per_gpu_mb: 0
euler_gpu_model: ~ # if set to a specific GPU, then the euler_gpu_min_mem_per_gpu_mb is ignored
euler_env: gcc/8.2.0 python/3.9.9

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"

docker_image_id: mpspdz
docker_image_tag: latest