---

instance_type: c5.9xlarge
ec2_volume_size: 300

# Fresh ubuntu 22.04
ec2_image_id: ami-07652eda1fbad7432
ec2_volume_snapshot: snap-0e68fbd89b6ec1b9e

instance_role: EC2WithS3Role

euler_job_minutes: 120 # individual job time
euler_cpu_cores: 4
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0
euler_gpu_min_mem_per_gpu_mb: 0
euler_gpu_model: ~ # if set to a specific GPU, then the euler_gpu_min_mem_per_gpu_mb is ignored
euler_env: gcc/8.2.0 python/3.9.9

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"

docker_image_id: mpspdz
docker_image_tag: latest