---

instance_type: c5.9xlarge # TODO: choose instance type
ec2_volume_size: 40 # TODO: choose volume size

ec2_image_id: ami-0f0b0c83671a44d44
ec2_volume_snapshot: snap-012df32896214a7e8


#  TODO [nku]: Nicolas, these should have sensible defaults or something
euler_job_minutes: 120 # individual job time
euler_cpu_cores: 4
euler_cpu_mem: 3072
euler_gpu_number: 1
euler_gpu_mem: 2000

euler_env: "gcc/8.2.0 python_gpu/3.9.9"

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"
